spring:
  application:
    name: performance-counter
  redis:
    database: 1
    client-type: lettuce
    host: 150.158.133.220
    port: 6379
    password:
    lettuce:
      pool:
        # 最大等待时间
        max-wait: 2000
        # 最大连接数
        max-active: 100
        # 最大空闲连接
        max-idle: 20
        # 最小空闲连接
        min-idle: 10